name: Test and build DynaBridge

on:
  push:
    branches: [main]

env:
  AWS_REGION: 'eu-central-1'

permissions:
  id-token: write
  contents: read

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node@20
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run format check
        run: |
          npm run format:check

      - name: Run tests
        run: |
          npm run test

      - name: Deploy
        run: |
          npm run build
